import type { Allergen, ItemTag, Nutrition, Unit } from '@prochia/shared';

/**
 * Demo content for a new branch. Nutrition is per 100 g/ml (or per piece) from standard food
 * tables; costs are illustrative toman prices per kilogram/litre/piece. Replace freely.
 */

type N = [
  kcal: number,
  protein: number,
  carbs: number,
  fat: number,
  fiber: number,
  sugar: number,
  sodium: number,
];
const n = ([kcal, protein, carbs, fat, fiber, sugar, sodium]: N): Nutrition => ({
  kcal,
  protein,
  carbs,
  fat,
  fiber,
  sugar,
  sodium,
});

export interface IngredientSeed {
  key: string;
  name: string;
  kind: 'raw' | 'prepared';
  unit: Unit;
  nutrition: Nutrition;
  allergens?: Allergen[];
  /** Toman per kg / litre / piece (raw only — prepared costs come from processing). */
  bulkPrice?: number;
  lowStock: number;
  /** Initial purchase, in kg / litres / pieces. */
  stock?: number;
}

export const INGREDIENTS: IngredientSeed[] = [
  {
    key: 'chicken',
    name: 'سینه مرغ خام',
    kind: 'raw',
    unit: 'g',
    nutrition: n([120, 22.5, 0, 2.6, 0, 0, 45]),
    bulkPrice: 380_000,
    lowStock: 5000,
    stock: 30,
  },
  {
    key: 'beef',
    name: 'راسته گوساله',
    kind: 'raw',
    unit: 'g',
    nutrition: n([160, 21, 0, 8, 0, 0, 55]),
    bulkPrice: 1_250_000,
    lowStock: 3000,
    stock: 12,
  },
  {
    key: 'trout',
    name: 'فیله قزل‌آلا',
    kind: 'raw',
    unit: 'g',
    nutrition: n([141, 20, 0, 6.2, 0, 0, 52]),
    allergens: ['fish'],
    bulkPrice: 950_000,
    lowStock: 2000,
    stock: 8,
  },
  {
    key: 'tuna',
    name: 'تن ماهی کنسروی',
    kind: 'raw',
    unit: 'g',
    nutrition: n([116, 25.5, 0, 0.8, 0, 0, 247]),
    allergens: ['fish'],
    bulkPrice: 700_000,
    lowStock: 1000,
    stock: 5,
  },
  {
    key: 'egg',
    name: 'تخم‌مرغ',
    kind: 'raw',
    unit: 'pcs',
    nutrition: n([72, 6.3, 0.4, 4.8, 0, 0.2, 71]),
    allergens: ['egg'],
    bulkPrice: 12_000,
    lowStock: 30,
    stock: 180,
  },
  {
    key: 'eggWhite',
    name: 'سفیده تخم‌مرغ پاستوریزه',
    kind: 'raw',
    unit: 'g',
    nutrition: n([52, 10.9, 0.7, 0.2, 0, 0.7, 166]),
    allergens: ['egg'],
    bulkPrice: 320_000,
    lowStock: 2000,
    stock: 10,
  },
  {
    key: 'brownRice',
    name: 'برنج قهوه‌ای',
    kind: 'raw',
    unit: 'g',
    nutrition: n([367, 7.5, 76, 3.2, 3.5, 0.9, 7]),
    bulkPrice: 230_000,
    lowStock: 3000,
    stock: 15,
  },
  {
    key: 'whiteRice',
    name: 'برنج ایرانی',
    kind: 'raw',
    unit: 'g',
    nutrition: n([360, 7, 79, 0.6, 1.3, 0.1, 1]),
    bulkPrice: 260_000,
    lowStock: 3000,
    stock: 10,
  },
  {
    key: 'quinoa',
    name: 'کینوآ',
    kind: 'raw',
    unit: 'g',
    nutrition: n([368, 14, 64, 6, 7, 0, 5]),
    bulkPrice: 950_000,
    lowStock: 1000,
    stock: 5,
  },
  {
    key: 'sweetPotato',
    name: 'سیب‌زمینی شیرین',
    kind: 'raw',
    unit: 'g',
    nutrition: n([86, 1.6, 20, 0.1, 3, 4.2, 55]),
    bulkPrice: 130_000,
    lowStock: 3000,
    stock: 15,
  },
  {
    key: 'lentil',
    name: 'عدس',
    kind: 'raw',
    unit: 'g',
    nutrition: n([352, 24.6, 63, 1.1, 10.7, 2, 6]),
    bulkPrice: 190_000,
    lowStock: 1000,
    stock: 5,
  },
  {
    key: 'chickpea',
    name: 'نخود',
    kind: 'raw',
    unit: 'g',
    nutrition: n([364, 19, 61, 6, 17, 10.7, 24]),
    bulkPrice: 210_000,
    lowStock: 1000,
    stock: 5,
  },
  {
    key: 'broccoli',
    name: 'بروکلی',
    kind: 'raw',
    unit: 'g',
    nutrition: n([34, 2.8, 6.6, 0.4, 2.6, 1.7, 33]),
    bulkPrice: 160_000,
    lowStock: 2000,
    stock: 10,
  },
  {
    key: 'mushroom',
    name: 'قارچ',
    kind: 'raw',
    unit: 'g',
    nutrition: n([22, 3.1, 3.3, 0.3, 1, 2, 5]),
    bulkPrice: 190_000,
    lowStock: 1000,
    stock: 5,
  },
  {
    key: 'onion',
    name: 'پیاز',
    kind: 'raw',
    unit: 'g',
    nutrition: n([40, 1.1, 9.3, 0.1, 1.7, 4.2, 4]),
    bulkPrice: 45_000,
    lowStock: 1000,
    stock: 5,
  },
  {
    key: 'spinach',
    name: 'اسفناج',
    kind: 'raw',
    unit: 'g',
    nutrition: n([23, 2.9, 3.6, 0.4, 2.2, 0.4, 79]),
    bulkPrice: 90_000,
    lowStock: 1000,
    stock: 4,
  },
  {
    key: 'lettuce',
    name: 'کاهو',
    kind: 'raw',
    unit: 'g',
    nutrition: n([15, 1.4, 2.9, 0.2, 1.3, 0.8, 28]),
    bulkPrice: 70_000,
    lowStock: 1500,
    stock: 6,
  },
  {
    key: 'tomato',
    name: 'گوجه‌فرنگی',
    kind: 'raw',
    unit: 'g',
    nutrition: n([18, 0.9, 3.9, 0.2, 1.2, 2.6, 5]),
    bulkPrice: 55_000,
    lowStock: 1500,
    stock: 8,
  },
  {
    key: 'cucumber',
    name: 'خیار',
    kind: 'raw',
    unit: 'g',
    nutrition: n([15, 0.7, 3.6, 0.1, 0.5, 1.7, 2]),
    bulkPrice: 45_000,
    lowStock: 1500,
    stock: 8,
  },
  {
    key: 'avocado',
    name: 'آووکادو',
    kind: 'raw',
    unit: 'g',
    nutrition: n([160, 2, 8.5, 14.7, 6.7, 0.7, 7]),
    bulkPrice: 1_600_000,
    lowStock: 500,
    stock: 3,
  },
  {
    key: 'oliveOil',
    name: 'روغن زیتون',
    kind: 'raw',
    unit: 'ml',
    nutrition: n([884, 0, 0, 100, 0, 0, 0]),
    bulkPrice: 950_000,
    lowStock: 500,
    stock: 4,
  },
  {
    key: 'spice',
    name: 'ادویه مرینیت',
    kind: 'raw',
    unit: 'g',
    nutrition: n([250, 10, 45, 5, 20, 5, 3000]),
    bulkPrice: 800_000,
    lowStock: 300,
    stock: 2,
  },
  {
    key: 'soy',
    name: 'سس سویا کم‌نمک',
    kind: 'raw',
    unit: 'ml',
    nutrition: n([53, 8, 5, 0, 0, 0.4, 3500]),
    allergens: ['soy', 'gluten'],
    bulkPrice: 420_000,
    lowStock: 300,
    stock: 2,
  },
  {
    key: 'tortilla',
    name: 'نان تورتیلا سبوس‌دار',
    kind: 'raw',
    unit: 'pcs',
    nutrition: n([170, 5, 28, 4, 4, 1, 350]),
    allergens: ['gluten'],
    bulkPrice: 16_000,
    lowStock: 20,
    stock: 80,
  },
  {
    key: 'feta',
    name: 'پنیر فتا کم‌چرب',
    kind: 'raw',
    unit: 'g',
    nutrition: n([215, 17, 4, 14, 0, 4, 900]),
    allergens: ['dairy', 'lactose'],
    bulkPrice: 520_000,
    lowStock: 500,
    stock: 3,
  },
  {
    key: 'greekYogurt',
    name: 'ماست یونانی کم‌چرب',
    kind: 'raw',
    unit: 'g',
    nutrition: n([73, 10, 3.9, 1.9, 0, 3.6, 36]),
    allergens: ['dairy', 'lactose'],
    bulkPrice: 260_000,
    lowStock: 2000,
    stock: 12,
  },
  {
    key: 'milk',
    name: 'شیر کم‌چرب',
    kind: 'raw',
    unit: 'ml',
    nutrition: n([42, 3.4, 5, 1, 0, 5, 44]),
    allergens: ['dairy', 'lactose'],
    bulkPrice: 65_000,
    lowStock: 4000,
    stock: 30,
  },
  {
    key: 'almondMilk',
    name: 'شیر بادام',
    kind: 'raw',
    unit: 'ml',
    nutrition: n([15, 0.6, 0.3, 1.2, 0.2, 0, 72]),
    allergens: ['nuts'],
    bulkPrice: 260_000,
    lowStock: 2000,
    stock: 12,
  },
  {
    key: 'whey',
    name: 'پودر وی ایزوله',
    kind: 'raw',
    unit: 'g',
    nutrition: n([390, 78, 8, 6, 0, 5, 200]),
    allergens: ['dairy'],
    bulkPrice: 4_800_000,
    lowStock: 1000,
    stock: 5,
  },
  {
    key: 'oats',
    name: 'جو دوسر پرک',
    kind: 'raw',
    unit: 'g',
    nutrition: n([389, 16.9, 66, 6.9, 10.6, 1, 2]),
    allergens: ['gluten'],
    bulkPrice: 210_000,
    lowStock: 1000,
    stock: 6,
  },
  {
    key: 'banana',
    name: 'موز',
    kind: 'raw',
    unit: 'g',
    nutrition: n([89, 1.1, 22.8, 0.3, 2.6, 12.2, 1]),
    bulkPrice: 160_000,
    lowStock: 2000,
    stock: 12,
  },
  {
    key: 'peanutButter',
    name: 'کره بادام‌زمینی',
    kind: 'raw',
    unit: 'g',
    nutrition: n([588, 25, 20, 50, 6, 9, 17]),
    allergens: ['peanut'],
    bulkPrice: 720_000,
    lowStock: 500,
    stock: 3,
  },
  {
    key: 'chia',
    name: 'دانه چیا',
    kind: 'raw',
    unit: 'g',
    nutrition: n([486, 16.5, 42, 30.7, 34.4, 0, 16]),
    bulkPrice: 1_300_000,
    lowStock: 500,
    stock: 3,
  },
  {
    key: 'honey',
    name: 'عسل',
    kind: 'raw',
    unit: 'g',
    nutrition: n([304, 0.3, 82, 0, 0.2, 82, 4]),
    bulkPrice: 850_000,
    lowStock: 300,
    stock: 2,
  },
  {
    key: 'dates',
    name: 'خرمای مضافتی',
    kind: 'raw',
    unit: 'g',
    nutrition: n([282, 2.5, 75, 0.4, 8, 63, 2]),
    bulkPrice: 260_000,
    lowStock: 500,
    stock: 4,
  },
  {
    key: 'almond',
    name: 'بادام درختی',
    kind: 'raw',
    unit: 'g',
    nutrition: n([579, 21, 22, 50, 12.5, 4.4, 1]),
    allergens: ['nuts'],
    bulkPrice: 1_450_000,
    lowStock: 500,
    stock: 3,
  },
  {
    key: 'cocoa',
    name: 'پودر کاکائو خالص',
    kind: 'raw',
    unit: 'g',
    nutrition: n([228, 19.6, 57.9, 13.7, 37, 1.8, 21]),
    bulkPrice: 950_000,
    lowStock: 200,
    stock: 2,
  },
  {
    key: 'strawberry',
    name: 'توت‌فرنگی منجمد',
    kind: 'raw',
    unit: 'g',
    nutrition: n([32, 0.7, 7.7, 0.3, 2, 4.9, 1]),
    bulkPrice: 320_000,
    lowStock: 1000,
    stock: 6,
  },
  {
    key: 'granola',
    name: 'گرانولای بدون شکر',
    kind: 'raw',
    unit: 'g',
    nutrition: n([450, 10, 60, 18, 8, 12, 50]),
    allergens: ['gluten', 'nuts'],
    bulkPrice: 740_000,
    lowStock: 500,
    stock: 4,
  },
  {
    key: 'coffee',
    name: 'دانه قهوه عربیکا',
    kind: 'raw',
    unit: 'g',
    nutrition: n([10, 0.6, 1.5, 0.1, 0, 0, 1]),
    bulkPrice: 2_100_000,
    lowStock: 1000,
    stock: 6,
  },

  // Ready-to-cook ingredients produced in the kitchen from the raw ones above.
  {
    key: 'chickenReady',
    name: 'مرغ مرینیت آماده گریل',
    kind: 'prepared',
    unit: 'g',
    nutrition: n([150, 23.9, 0.9, 4.9, 0.4, 0.1, 110]),
    lowStock: 2000,
  },
  {
    key: 'beefReady',
    name: 'گوساله مرینیت تریاکی',
    kind: 'prepared',
    unit: 'g',
    nutrition: n([173, 22.5, 0.6, 8.5, 0.2, 0.1, 200]),
    allergens: ['soy', 'gluten'],
    lowStock: 1500,
  },
  {
    key: 'troutReady',
    name: 'قزل‌آلای مرینیت',
    kind: 'prepared',
    unit: 'g',
    nutrition: n([162, 20.7, 0.5, 7.9, 0.2, 0, 85]),
    allergens: ['fish'],
    lowStock: 1000,
  },
  {
    key: 'brownRiceCooked',
    name: 'برنج قهوه‌ای پخته',
    kind: 'prepared',
    unit: 'g',
    nutrition: n([131, 2.7, 27, 1.1, 1.3, 0.3, 3]),
    lowStock: 2000,
  },
  {
    key: 'whiteRiceCooked',
    name: 'برنج ایرانی پخته',
    kind: 'prepared',
    unit: 'g',
    nutrition: n([120, 2.3, 26.3, 0.2, 0.4, 0, 1]),
    lowStock: 1500,
  },
  {
    key: 'quinoaCooked',
    name: 'کینوآ پخته',
    kind: 'prepared',
    unit: 'g',
    nutrition: n([136, 5.2, 23.7, 2.2, 2.6, 0, 2]),
    lowStock: 1000,
  },
  {
    key: 'sweetPotatoRoasted',
    name: 'سیب‌زمینی شیرین تنوری',
    kind: 'prepared',
    unit: 'g',
    nutrition: n([130, 2, 25, 2.6, 3.8, 5.2, 69]),
    lowStock: 1500,
  },
  {
    key: 'legumes',
    name: 'خوراک عدس و نخود',
    kind: 'prepared',
    unit: 'g',
    nutrition: n([143, 8.7, 24.8, 1.4, 5.5, 2.5, 6]),
    lowStock: 1000,
  },
  {
    key: 'vegSteamed',
    name: 'سبزیجات بخارپز',
    kind: 'prepared',
    unit: 'g',
    nutrition: n([34.5, 2.7, 6.8, 0.4, 2.2, 2.4, 23]),
    lowStock: 1500,
  },
  {
    key: 'chiaBase',
    name: 'پایه پودینگ چیا',
    kind: 'prepared',
    unit: 'g',
    nutrition: n([104, 3.1, 10.9, 5.9, 5.5, 3.9, 60]),
    allergens: ['nuts'],
    lowStock: 1000,
  },
  {
    key: 'coldBrew',
    name: 'کنسانتره کلدبرو',
    kind: 'prepared',
    unit: 'ml',
    nutrition: n([2, 0.1, 0.3, 0, 0, 0, 3]),
    lowStock: 1000,
  },
];

export interface PrepSeed {
  name: string;
  output: string;
  outputQuantity: number;
  inputs: [string, number][];
  /** Batches to run while seeding. */
  runs: number;
}

/** "Processing" definitions: raw → ready-to-cook, with realistic yields. */
export const PREP_RECIPES: PrepSeed[] = [
  {
    name: 'تمیز و مرینیت سینه مرغ',
    output: 'chickenReady',
    outputQuantity: 950,
    inputs: [
      ['chicken', 1000],
      ['spice', 20],
      ['oliveOil', 20],
    ],
    runs: 12,
  },
  {
    name: 'مرینیت گوساله تریاکی',
    output: 'beefReady',
    outputQuantity: 950,
    inputs: [
      ['beef', 1000],
      ['soy', 30],
      ['spice', 10],
    ],
    runs: 5,
  },
  {
    name: 'مرینیت قزل‌آلا',
    output: 'troutReady',
    outputQuantity: 970,
    inputs: [
      ['trout', 1000],
      ['oliveOil', 15],
      ['spice', 10],
    ],
    runs: 3,
  },
  {
    name: 'پخت برنج قهوه‌ای',
    output: 'brownRiceCooked',
    outputQuantity: 2800,
    inputs: [['brownRice', 1000]],
    runs: 4,
  },
  {
    name: 'پخت برنج ایرانی',
    output: 'whiteRiceCooked',
    outputQuantity: 3000,
    inputs: [['whiteRice', 1000]],
    runs: 2,
  },
  {
    name: 'پخت کینوآ',
    output: 'quinoaCooked',
    outputQuantity: 2700,
    inputs: [['quinoa', 1000]],
    runs: 2,
  },
  {
    name: 'تنوری کردن سیب‌زمینی شیرین',
    output: 'sweetPotatoRoasted',
    outputQuantity: 800,
    inputs: [
      ['sweetPotato', 1000],
      ['oliveOil', 20],
    ],
    runs: 6,
  },
  {
    name: 'پخت عدس و نخود',
    output: 'legumes',
    outputQuantity: 2500,
    inputs: [
      ['lentil', 500],
      ['chickpea', 500],
    ],
    runs: 2,
  },
  {
    name: 'بخارپز کردن سبزیجات',
    output: 'vegSteamed',
    outputQuantity: 950,
    inputs: [
      ['broccoli', 600],
      ['mushroom', 200],
      ['onion', 200],
    ],
    runs: 6,
  },
  {
    name: 'پایه پودینگ چیا (۱۲ ساعت یخچال)',
    output: 'chiaBase',
    outputQuantity: 1250,
    inputs: [
      ['chia', 200],
      ['almondMilk', 1000],
      ['honey', 60],
    ],
    runs: 3,
  },
  {
    name: 'دم کردن کلدبرو (۱۸ ساعت)',
    output: 'coldBrew',
    outputQuantity: 1000,
    inputs: [['coffee', 250]],
    runs: 2,
  },
];

export interface ItemSeed {
  key: string;
  category: string;
  name: string;
  description: string;
  price: number;
  tags: ItemTag[];
  allergens: Allergen[];
  prepMinutes: number;
  recipe: [string, number][];
  groups?: string[];
  creditEligible?: boolean;
}

export const CATEGORIES: { key: string; name: string; station: 'restaurant' | 'cafe' }[] = [
  { key: 'bowls', name: 'کاسه‌های پروتئین', station: 'restaurant' },
  { key: 'wraps', name: 'رپ و سالاد', station: 'restaurant' },
  { key: 'breakfast', name: 'صبحانه ورزشی', station: 'restaurant' },
  { key: 'shakes', name: 'شیک پروتئین', station: 'cafe' },
  { key: 'coffee', name: 'قهوه', station: 'cafe' },
  { key: 'snacks', name: 'میان‌وعده', station: 'cafe' },
];

export const ITEMS: ItemSeed[] = [
  {
    key: 'chickenBowl',
    category: 'bowls',
    name: 'بول مرغ گریل',
    description: 'سینه مرغ مرینیت روی زغال، برنج قهوه‌ای و سبزیجات بخارپز با روغن زیتون.',
    price: 485_000,
    tags: ['high_protein', 'post_workout', 'gluten_free'],
    allergens: [],
    prepMinutes: 14,
    recipe: [
      ['chickenReady', 200],
      ['brownRiceCooked', 180],
      ['vegSteamed', 120],
      ['oliveOil', 5],
    ],
    groups: ['carb', 'extraProtein'],
  },
  {
    key: 'beefBowl',
    category: 'bowls',
    name: 'بول گوساله تریاکی',
    description: 'راسته گوساله با سس تریاکی کم‌نمک، سیب‌زمینی شیرین تنوری و سبزیجات.',
    price: 690_000,
    tags: ['high_protein', 'post_workout'],
    allergens: ['soy', 'gluten'],
    prepMinutes: 16,
    recipe: [
      ['beefReady', 180],
      ['sweetPotatoRoasted', 200],
      ['vegSteamed', 100],
    ],
    groups: ['extraProtein'],
  },
  {
    key: 'troutBowl',
    category: 'bowls',
    name: 'بول قزل‌آلا و کینوآ',
    description: 'قزل‌آلای گریل، کینوآ، اسفناج تازه و آووکادو.',
    price: 720_000,
    tags: ['high_protein', 'post_workout', 'gluten_free'],
    allergens: ['fish'],
    prepMinutes: 15,
    recipe: [
      ['troutReady', 180],
      ['quinoaCooked', 150],
      ['spinach', 40],
      ['avocado', 40],
    ],
  },
  {
    key: 'veganBowl',
    category: 'bowls',
    name: 'بول گیاهی عدس و نخود',
    description: 'خوراک عدس و نخود، کینوآ، سبزی تازه و روغن زیتون. پرفیبر و سیرکننده.',
    price: 390_000,
    tags: ['vegan', 'vegetarian', 'gluten_free'],
    allergens: [],
    prepMinutes: 10,
    recipe: [
      ['legumes', 250],
      ['quinoaCooked', 100],
      ['spinach', 40],
      ['tomato', 60],
      ['cucumber', 60],
      ['oliveOil', 10],
    ],
  },
  {
    key: 'chickenWrap',
    category: 'wraps',
    name: 'رپ مرغ و آووکادو',
    description: 'نان تورتیلا سبوس‌دار، مرغ گریل، آووکادو، کاهو و سس ماست.',
    price: 420_000,
    tags: ['high_protein'],
    allergens: ['gluten', 'dairy'],
    prepMinutes: 8,
    recipe: [
      ['tortilla', 1],
      ['chickenReady', 150],
      ['avocado', 40],
      ['lettuce', 30],
      ['tomato', 40],
      ['greekYogurt', 30],
    ],
    groups: ['extraProtein'],
  },
  {
    key: 'chickenSalad',
    category: 'wraps',
    name: 'سالاد مرغ گریل',
    description: 'مرغ گریل، کاهو، گوجه، خیار و فتای کم‌چرب با روغن زیتون.',
    price: 450_000,
    tags: ['high_protein', 'low_carb', 'keto', 'gluten_free'],
    allergens: ['dairy'],
    prepMinutes: 7,
    recipe: [
      ['chickenReady', 150],
      ['lettuce', 100],
      ['tomato', 60],
      ['cucumber', 60],
      ['feta', 30],
      ['oliveOil', 10],
    ],
    groups: ['extraProtein'],
  },
  {
    key: 'tunaSalad',
    category: 'wraps',
    name: 'سالاد تن ماهی',
    description: 'تن ماهی، تخم‌مرغ آب‌پز، سبزیجات تازه و روغن زیتون.',
    price: 380_000,
    tags: ['high_protein', 'low_carb', 'gluten_free'],
    allergens: ['fish', 'egg'],
    prepMinutes: 6,
    recipe: [
      ['tuna', 120],
      ['lettuce', 80],
      ['tomato', 60],
      ['cucumber', 60],
      ['egg', 1],
      ['oliveOil', 10],
    ],
  },
  {
    key: 'omelette',
    category: 'breakfast',
    name: 'املت سفیده و اسفناج',
    description: 'سفیده تخم‌مرغ با یک زرده، اسفناج، قارچ و فتا.',
    price: 290_000,
    tags: ['high_protein', 'low_carb', 'vegetarian'],
    allergens: ['egg', 'dairy'],
    prepMinutes: 8,
    recipe: [
      ['eggWhite', 200],
      ['egg', 1],
      ['spinach', 60],
      ['mushroom', 50],
      ['feta', 20],
      ['oliveOil', 5],
    ],
  },
  {
    key: 'oatmeal',
    category: 'breakfast',
    name: 'اوتمیل پروتئینی موز و چیا',
    description: 'جو دوسر پخته در شیر با وی، موز، دانه چیا و کمی عسل. انرژی قبل از تمرین.',
    price: 320_000,
    tags: ['pre_workout', 'high_protein', 'vegetarian'],
    allergens: ['dairy', 'lactose', 'gluten'],
    prepMinutes: 6,
    recipe: [
      ['oats', 60],
      ['whey', 25],
      ['milk', 200],
      ['banana', 80],
      ['chia', 10],
      ['honey', 10],
    ],
  },
  {
    key: 'bananaShake',
    category: 'shakes',
    name: 'شیک موز و کره بادام‌زمینی',
    description: 'یک اسکوپ وی ایزوله، شیر کم‌چرب، موز و کره بادام‌زمینی.',
    price: 265_000,
    tags: ['high_protein', 'post_workout'],
    allergens: ['dairy', 'lactose', 'peanut'],
    prepMinutes: 3,
    recipe: [
      ['whey', 30],
      ['milk', 250],
      ['banana', 100],
      ['peanutButter', 15],
    ],
    creditEligible: false,
  },
  {
    key: 'chocoShake',
    category: 'shakes',
    name: 'شیک شکلات پروتئین',
    description: 'وی ایزوله، شیر بادام، کاکائوی خالص و خرما. بدون شکر افزوده.',
    price: 245_000,
    tags: ['high_protein', 'post_workout', 'low_fat'],
    allergens: ['dairy', 'nuts'],
    prepMinutes: 3,
    recipe: [
      ['whey', 30],
      ['almondMilk', 300],
      ['cocoa', 10],
      ['dates', 20],
    ],
    creditEligible: false,
  },
  {
    key: 'berryShake',
    category: 'shakes',
    name: 'شیک توت‌فرنگی و ماست یونانی',
    description: 'ماست یونانی، توت‌فرنگی، نصف اسکوپ وی و کمی عسل.',
    price: 255_000,
    tags: ['high_protein', 'low_fat', 'post_workout'],
    allergens: ['dairy', 'lactose'],
    prepMinutes: 3,
    recipe: [
      ['greekYogurt', 200],
      ['strawberry', 150],
      ['honey', 15],
      ['whey', 15],
    ],
    creditEligible: false,
  },
  {
    key: 'espresso',
    category: 'coffee',
    name: 'اسپرسو',
    description: 'دبل شات عربیکا.',
    price: 95_000,
    tags: ['caffeine', 'pre_workout', 'vegan'],
    allergens: [],
    prepMinutes: 2,
    recipe: [['coffee', 18]],
    creditEligible: false,
  },
  {
    key: 'americano',
    category: 'coffee',
    name: 'آمریکانو',
    description: 'دبل شات با آب داغ.',
    price: 105_000,
    tags: ['caffeine', 'pre_workout', 'vegan'],
    allergens: [],
    prepMinutes: 2,
    recipe: [['coffee', 18]],
    creditEligible: false,
  },
  {
    key: 'latte',
    category: 'coffee',
    name: 'لاته',
    description: 'دبل شات با شیر کم‌چرب.',
    price: 145_000,
    tags: ['caffeine'],
    allergens: ['dairy', 'lactose'],
    prepMinutes: 3,
    recipe: [
      ['coffee', 18],
      ['milk', 220],
    ],
    groups: ['milk'],
    creditEligible: false,
  },
  {
    key: 'proteinLatte',
    category: 'coffee',
    name: 'لاته پروتئینی پروچیا',
    description: 'لاته با ۲۰ گرم وی وانیلی — کافئین و پروتئین قبل از تمرین.',
    price: 185_000,
    tags: ['caffeine', 'high_protein', 'pre_workout'],
    allergens: ['dairy', 'lactose'],
    prepMinutes: 3,
    recipe: [
      ['coffee', 18],
      ['milk', 200],
      ['whey', 20],
    ],
    groups: ['milk'],
    creditEligible: false,
  },
  {
    key: 'coldBrew',
    category: 'coffee',
    name: 'کلدبرو',
    description: 'دم‌آوری ۱۸ ساعته، سرد و ملایم.',
    price: 135_000,
    tags: ['caffeine', 'vegan'],
    allergens: [],
    prepMinutes: 1,
    recipe: [['coldBrew', 120]],
    creditEligible: false,
  },
  {
    key: 'chiaPudding',
    category: 'snacks',
    name: 'پودینگ چیا',
    description: 'چیا خیس‌خورده در شیر بادام با توت‌فرنگی و گرانولا. امضای پروچیا.',
    price: 195_000,
    tags: ['vegetarian'],
    allergens: ['nuts', 'gluten'],
    prepMinutes: 2,
    recipe: [
      ['chiaBase', 200],
      ['strawberry', 50],
      ['granola', 15],
    ],
    creditEligible: false,
  },
  {
    key: 'energyBalls',
    category: 'snacks',
    name: 'انرژی‌بال خرما و بادام',
    description: 'دو عدد؛ خرما، بادام، جو دوسر و کاکائو. سوخت سریع قبل از تمرین.',
    price: 120_000,
    tags: ['pre_workout', 'vegan', 'vegetarian'],
    allergens: ['nuts', 'gluten'],
    prepMinutes: 1,
    recipe: [
      ['dates', 40],
      ['almond', 20],
      ['oats', 10],
      ['cocoa', 5],
    ],
    creditEligible: false,
  },
  {
    key: 'yogurtBowl',
    category: 'snacks',
    name: 'ماست یونانی با گرانولا',
    description: 'ماست یونانی، گرانولای بدون شکر، موز و عسل.',
    price: 210_000,
    tags: ['high_protein', 'vegetarian', 'pre_workout'],
    allergens: ['dairy', 'lactose', 'gluten'],
    prepMinutes: 2,
    recipe: [
      ['greekYogurt', 200],
      ['granola', 30],
      ['honey', 10],
      ['banana', 50],
    ],
    creditEligible: false,
  },
];

export interface GroupSeed {
  key: string;
  name: string;
  minSelect: number;
  maxSelect: number;
  options: {
    name: string;
    priceDelta: number;
    isDefault?: boolean;
    recipe: [string, number][];
  }[];
}

/** Option nutrition is derived from the option recipe when seeding. */
export const GROUPS: GroupSeed[] = [
  {
    key: 'carb',
    name: 'پایه کربوهیدرات',
    minSelect: 1,
    maxSelect: 1,
    options: [
      { name: 'برنج قهوه‌ای', priceDelta: 0, isDefault: true, recipe: [] },
      {
        name: 'برنج ایرانی',
        priceDelta: 0,
        recipe: [
          ['brownRiceCooked', -180],
          ['whiteRiceCooked', 180],
        ],
      },
      {
        name: 'کینوآ',
        priceDelta: 60_000,
        recipe: [
          ['brownRiceCooked', -180],
          ['quinoaCooked', 180],
        ],
      },
      {
        name: 'بدون کربو، سبزیجات دوبل',
        priceDelta: 0,
        recipe: [
          ['brownRiceCooked', -180],
          ['vegSteamed', 150],
        ],
      },
    ],
  },
  {
    key: 'extraProtein',
    name: 'پروتئین اضافه',
    minSelect: 0,
    maxSelect: 1,
    options: [
      { name: '۱۰۰ گرم مرغ اضافه', priceDelta: 160_000, recipe: [['chickenReady', 100]] },
      { name: '۱۰۰ گرم گوساله اضافه', priceDelta: 340_000, recipe: [['beefReady', 100]] },
      { name: 'دو سفیده آب‌پز', priceDelta: 45_000, recipe: [['eggWhite', 66]] },
    ],
  },
  {
    key: 'milk',
    name: 'نوع شیر',
    minSelect: 1,
    maxSelect: 1,
    options: [
      { name: 'شیر کم‌چرب', priceDelta: 0, isDefault: true, recipe: [] },
      {
        name: 'شیر بادام',
        priceDelta: 30_000,
        recipe: [
          ['milk', -200],
          ['almondMilk', 200],
        ],
      },
    ],
  },
];
